spring.application.name=ParkingLotSimulator

logging.pattern.console=%d{HH:mm:ss} %clr(%-5level) %logger{20} : %msg%n

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=when-authorized
